name: 'Copy Secrets'
description: 'Copy secret information for server'
inputs:
  profile:
    description: 'profile which secret belong to'
    required: true
  oauth-secret:
    description: 'oauth secret file'
    required: true
  s3-secret:
    description: 's3 secret file'
    required: true
  fcm-secret-file:
    description: 'fcm secret file'
    required: true
  fcm-secret-file-name:
    description: 'fcm secret file name'
    required: true
  fcm-secret-config:
    description: 'fcm secret config file'
    required: true
  dev-db-secret:
    description: 'development db secret file'
  prod-db-secret:
    description: 'production db secret file'

runs:
  using: "composite"
  steps:
  - name: Copy Oauth and S3 key
    env:
      OAUTH_SECRET: ${{ inputs.oauth-secret }}
      OAUTH_SECRET_DIR_FILE_NAME: application-oauth.yml
      S3_SECRET: ${{ inputs.s3-secret }}
      S3_SECRET_DIR_FILE_NAME: application-s3.yml
      SECRET_DIR: src/main/resources
    shell: bash
    run: | 
      echo $OAUTH_SECRET | base64 --decode > $SECRET_DIR/$OAUTH_SECRET_DIR_FILE_NAME
      echo $S3_SECRET | base64 --decode > $SECRET_DIR/$S3_SECRET_DIR_FILE_NAME

  - name: Copy FCM secrets
    env:
      FCM_SECRET: ${{ inputs.fcm-secret-file }}
      FCM_SECRET_FILE_NAME : ${{ inputs.fcm-secret-file-name }}
      FCM_SECRET_DIR: src/main/resources/secret
      FCM_SECRET_CONFIG: ${{ inputs.fcm-secret-config }}
      FCM_SECRET_CONFIG_FILE_NAME: application-fcm.yml
      FCM_SECRET_CONFIG_DIR: src/main/resources
    shell: bash
    run: |
      mkdir $FCM_SECRET_DIR
      echo $FCM_SECRET | base64 --decode > $FCM_SECRET_DIR/$FCM_SECRET_FILE_NAME
      echo $FCM_SECRET_CONFIG | base64 --decode > $FCM_SECRET_CONFIG_DIR/$FCM_SECRET_CONFIG_FILE_NAME

  - name: Copy Dev DB Secrets
    if: inputs.profile == 'dev'
    env:
      DEV_DB_SECRET: ${{ inputs.dev-db-secret }}
      DEV_DB_DIR_FILE_NAME: application-dev-db.yml
      SECRET_DIR: src/main/resources
    shell: bash
    run: echo $DEV_DB_SECRET | base64 --decode > $SECRET_DIR/$DEV_DB_DIR_FILE_NAME

  - name: Copy Prod DB Secrets
    if: inputs.profile == 'prod'
    env:
      PROD_DB_SECRET: ${{ inputs.prod-db-secret }}
      PROD_DB_SECRET_DIR: src/main/resources
      PROD_DB_DIR_FILE_NAME: application-prod-db.yml
      SECRET_DIR: src/main/resources
    shell: bash
    run: echo $PROD_DB_SECRET | base64 --decode > $SECRET_DIR/$PROD_DB_DIR_FILE_NAME

