name: test before merging


on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set execute permissions for Gradle wrapper
        run: chmod +x gradlew

      - name: Copy Secrets
        uses: ./.github/actions/copy_secret
        with:
          profile: local
          oauth-secret: ${{ secrets.OAUTH_SECRET }}
          s3-secret: ${{ secrets.S3_SECRET }}
          fcm-secret-file: ${{ secrets.FCM_SECRET }}
          fcm-secret-file-name: ${{ secrets.FCM_SECRET_FILE_NAME }}
          fcm-secret-config: ${{ secrets.FCM_SECRET_CONFIG }}

      - name: Run MySQL image for test
        run: docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=local_db mysql:8.0.31

      - name: Test with Gradle
        run: ./gradlew test

      - name: Test Fail Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 'Test Fail Notification'
          text: '테스트에 실패했습니다.'
          fields: repo,commit,author,ref,workflow,job,took,pullRequest
          mention: 'U05BT7J8YV8,U05BT2V4C58'
          if_mention: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BACKEND_WEBHOOK_URL }} # required
        if: failure()
